package com.nonetxmxy.mmzqfxy.base

object FinalKeys {
    val SP_NAME = "sp_name"
    val IS_LOGGED = "is_logged"
    val IS_TIPS = "is_tips"
    val PHONE_NUMBER = "phone_number"
    val SERVICE_NUMBER = "service_number"
    val EMAIL = "email"
    val TOKEN = "token"
    val CURRENT_PRO_CODE = "current_pro_code"
    val IS_S_ACCOUNT = "is_s_account"
    val IS_OLD_MAN = "is_old_man"
    val ADJUST_ID = "adjust_id"
    val LAST_SEND_CODE_TIME = "last_send_code_time"
    val LAST_SEND_VCODE_TIME = "last_send_voice_time"
    val PHOTO_INFO = "photo_info"
    val ID_TOP = "id_top"
    val ID_BeHIND = "id_behind"
    val FACE_PHOTO = "face_photo"
    val LONG_LOCATION = "long_location"
    val LATI_LOCATION = "lati_location"
    val ACCESS_KEY = "access_key"
    val SECRET_KEY = "secret_key"
    val FACE_LIVENESS_ID = "face_liveness_id"
}